Added infinite log gen

diff --git a/.github/workflows/docker-publish.yaml b/.github/workflows/docker-publish.yaml
--- a/.github/workflows/docker-publish.yaml
+++ b/.github/workflows/docker-publish.yaml
@@ -74,11 +74,11 @@ jobs:
           echo "Working Directory: $(pwd)"
           ls -la staging/internal-apps
 
-      - name: Update load-gen.yaml
-        run: |
-          sed -i "s|ghcr.io/ctrlb-hq/load-gen:.*|ghcr.io/ctrlb-hq/load-gen:$VERSION_TAG|" staging/internal-apps/load-gen.yaml
-          git config user.name "github-actions"
-          git config user.email "github-actions@github.com"
-          git add staging/internal-apps/load-gen.yaml
-          git commit -m "Update load-gen image to $VERSION_TAG" || echo "No changes to commit"
-          git push origin main || echo "Push failed; check permissions or branch protection rules"
+      # - name: Update load-gen.yaml
+      #   run: |
+      #     sed -i "s|ghcr.io/ctrlb-hq/load-gen:.*|ghcr.io/ctrlb-hq/load-gen:$VERSION_TAG|" staging/internal-apps/load-gen.yaml
+      #     git config user.name "github-actions"
+      #     git config user.email "github-actions@github.com"
+      #     git add staging/internal-apps/load-gen.yaml
+      #     git commit -m "Update load-gen image to $VERSION_TAG" || echo "No changes to commit"
+      #     git push origin main || echo "Push failed; check permissions or branch protection rules"
